# fly.toml app configuration file generated for tturna-fullstackopen-pokedex on 2024-03-04T18:48:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tturna-fullstackopen-pokedex'
primary_region = 'arn'

[build]

[env]
  PORT = "4200"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  strategy = "canary"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
  restart_limit = 3