name: Hello World Workflow!

on:
  push:
    branches:
    - main

jobs:
  say_hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: |
        echo "Hello World Workflow!"
