name: Deployment pipeline

on:
  push:
    branches:
      - main
  
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build
      
      - name: Test
        run: npm run test

      - name: E2E Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Check for skip
        id: check-skip
        env:
          SKIP: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: |
          echo "SKIP=$SKIP"
          echo "::set-output name=skip::$SKIP"
      
      - name: Setup Flyctl
        if: ${{ steps.check-skip.outputs.skip == 'false' && github.event_name == 'push' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        if: ${{ steps.check-skip.outputs.skip == 'false' && github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Notify Failure Discord
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
            severity: error
            description: |
              **Event:** ${{ github.event_name }}
              **Repo:** [${{ github.repository }}](https://github.com/${{ github.repository }})
              **Job:** ${{ github.job }}
              **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            details: Deploy Failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Success Discord
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: success()
        with:
            severity: info
            description: 'Testing: ${{ github.event.commits.*.id }}'
            details: Deploy Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ needs.simple_deployment_pipeline.outputs.skip == 'false' && github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch